---
name: "Test"

"on":
  pull_request:

jobs:
  ci:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Setup nodeJS"
        if: ${{ success() }}
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.0"

      - name: "Install dependencies"
        if: ${{ success() }}
        run: npm install

      - name: "Run unit tests"
        if: ${{ success() }}
        run: npm run test:unit
